### ISSUE TITLE
Try to login and list the latest grades

### ISSUE THREAD

**Issue by zmoog** [zmoog/axios#1]
This is for testing the available options.

I can think of the following questions:

- Are there some APIs available, or we need to scrape the website?
- tba

**Comment by zmoog** [comment]
The website URL is https://family.axioscloud.it/Secret/REStart.aspx?Customer_ID=<customer_id>

`customer_id` is something you should get from directly or indirectly from your school.

**Comment by zmoog** [comment]
My old Hogwarts project contains a working implementation of an Axios client (at least it was working back in the day).

See https://github.com/zmoog/hogwarts/blob/master/app/navigator.py

Let's try to extract the client into this project.

**Comment by zmoog** [comment]
I finally put together a basic script that can log into the Axios service:

```python
import requests
from lxml import html

from .models import Credentials, Profile

START_URL = 'https://family.axioscloud.it/Secret/REStart.aspx?Customer_ID='
FAMILY_URL = 'https://family.axioscloud.it/Secret/REFamily.aspx'


class Navigator:

    def __init__(self, credentials: Credentials):
        self.credentials = credentials
        self.session = requests.Session()

    def login(self) -> Profile:
        startUrl = START_URL + self.credentials.customer_id

        print("getting start page", startUrl)
        resp = self.session.get(startUrl)

        tree = html.fromstring(resp.text)

        viewstate = tree.xpath('//input[@id="__VIEWSTATE"]')
        viewstategenerator = tree.xpath('//input[@id="__VIEWSTATEGENERATOR"]')
        eventvalidation = tree.xpath('//input[@id="__EVENTVALIDATION"]')

        start_payload = {
            '__VIEWSTATE': viewstate[0].value,
            '__VIEWSTATEGENERATOR': viewstategenerator[0].value,
            '__EVENTVALIDATION': eventvalidation[0].value,
            'ibtnRE.x': 0,
            'ibtnRE.y': 0,
            'mha': "",
        }

        headers = {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Origin': 'https://family.axioscloud.it',
            'Referer': startUrl,
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'none',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36',
        }

        print("getting start page", startUrl)
        resp = self.session.post(startUrl, data=start_payload, headers=headers)

        print("headers", resp.headers)

        tree = html.fromstring(resp.text)

        viewstate = tree.xpath('//input[@id="__VIEWSTATE"]')
        viewstategenerator = tree.xpath('//input[@id="__VIEWSTATEGENERATOR"]')
        eventvalidation = tree.xpath('//input[@id="__EVENTVALIDATION"]')

        login_payload = {
            '__LASTFOCUS': "",
            '__VIEWSTATE': viewstate[0].value,
            '__VIEWSTATEGENERATOR': viewstategenerator[0].value,
            '__EVENTTARGET': "",
            '__EVENTVALIDATION': eventvalidation[0].value,
            'txtImproveDone': "",
            'txtUser': self.credentials.username,
            'txtPassword': self.credentials.password,
            'btnLogin': 'Accedi',
        }

        resp = self.session.post('https://family.axioscloud.it/Secret/RELogin.aspx', data=login_payload, headers=headers)

        # print(resp.text)
        tree = html.fromstring(resp.text)

        name = tree.xpath('//span[@id="lblUserName"]')

        if not name:
            raise Exception("Login failed")    
            
        return Profile(name[0].text)

        # viewstate = tree.xpath('//input[@id="__VIEWSTATE"]')
        # viewstategenerator = tree.xpath('//input[@id="__VIEWSTATEGENERATOR"]')
        # eventvalidation = tree.xpath('//input[@id="__EVENTVALIDATION"]')
```

Pretty brutal, but it works. Nice first step.

**Comment by zmoog** [comment]
The next step is to set up testing to use saved HTML pages. I want to execute something other than real login at each test execution.

I spent some time hacking some code to replay HTTP requests performed by the requests library, and then I discovered the fantastic https://github.com/kiwicom/pytest-recording, a pytest plugin that records network interactions in your tests via VCR.py.

Holy moly, pytest-recording and VCR.py are so helpful!

You can write a lean test like this:

```python
@pytest.mark.vcr(filter_query_parameters=["txtUser", "txtPassword"])
@pytest.mark.block_network
def test_login():
    runner = CliRunner()
    with runner.isolated_filesystem():
        result = runner.invoke(cli, ["login"])
        assert result.exit_code == 0
        assert "Logged in as BRANCA MAURIZIO (ISTITUTO COMPRENSIVO VEROLENGO)" in result.output
```

And execute it using:

```shell
$ pytest --record-mode=once tests/test_axios.py -vvv
============================================================ test session starts =============================================================
platform darwin -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0 -- /Users/zmoog/code/projects/zmoog/axios/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/zmoog/code/projects/zmoog/axios
plugins: recording-0.12.1
collected 2 items

tests/test_axios.py::test_version PASSED                                                                                               [ 50%]
tests/test_axios.py::test_login PASSED                                                                                                 [100%]

============================================================= 2 passed in 0.11s ==============================================================
```

The first time it will perform the network interactions to do the actual login on the Axios website. Each interaction is recorded locally in useful yaml file, like this one:

```yaml
interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - python-requests/2.28.1
    method: GET
    uri: https://family.axioscloud.it/Secret/REStart.aspx?Customer_ID=91014810013
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA9xa21IjORJ9no7of8ip3hggxrh8AdMMtidsY2j3cmtfuG1sOFSSXBZWSdWSysZs
        zP/ML+zz/NiGqsrYGANN0/Oy/YIrlTrKTGVKqcx+/+79u/LP+6eN7tVZE4Ym4NX378r2L3Ak/IrD
        jBNTKCLVckANAoECWnEI1Vix0DApHMBSGCpMxWlTn2mjJDQ5NUoKhmUGOnJgJkhRCKkCjkDjSHKU
        gU6r02kBE9CmhmagdsukzkCHac0uqOeA+2DBEZ1OpCJ6YbV4BrQM4gzN58foUCxtZ2ClOA0uI5KB
        djMDtTDMQEsYhQQ1qUCP5JoJNINeUOiekKx5gALmc4bmog+NCTfp14iNK04D4SHdtMIryRe0EHIT
        26HXzQoibTYVHSPOCDLJZMMMp9X3735qNx+qnuqemOj9u7KbcJY5EyNQlFeczqfTdrfR60KrcXri
        wFDRQcXJZt1WgHyq3Xazz7AU2VD4dqX37wCSyfeMHTPlVLudi2OkDVXJZxZr/Xtrv+Iki+iYOKTU
        OGCmIa04ht4aF2v9EuhsD7rI47TR6fwg4HZzZqYFK/0gbIMRz8Zc3wqTBNTi6A0ao4TqgFY4gY+/
        tXvzNaJqupnP5gvZrWzARPZGO9Wym/DHiN+BisIwxYpN8GY8IyU3LHws22txrDXfDII8j6rvhHHP
        eOQzcW94j0s86rXSz2z6uWojXl4iZQIYIwXaqCOkzT4yFCqwtrYHrgsHCAgCLxoMqJqdowQZBIRB
        ....
```

The network interactions are stored in the path `tests/cassettes/test_axios/<TEST_NAME>.yaml`.

Then, from the second execution on, it will use the recording saved in the yaml files to replay all interactions. No code changes or mocking is required.
