### ISSUE TITLE
Remove env variables from GitHub Actions workflow

### ISSUE THREAD

**Issue by zmoog** [zmoog/axios#4]
We should avoid setting environment variable in the GitHub Actions workflow: it makes the text longer and the result is less flexible.

**Comment by zmoog** [comment]
Instead of using:

```yaml
    - name: Run tests
      run: |
        pytest
      env:
        AXIOS_USERNAME: 'username'
        AXIOS_PASSWORD: 'password'
        AXIOS_CUSTOMER_ID: '91014810013'
```

I need to find something different.
